# Generated by Django 5.2 on 2025-11-22 19:15

from django.db import migrations

def cargar_preguntas(apps, schema_editor):
    PreguntaPerfil = apps.get_model("Aprendizaje_adaptativo", "PreguntaPerfil")

    preguntas = [
        ("Prefiero estudiar en bloques cortos de tiempo con descansos regulares (ej. 25 min estudio + 5 min descanso).", "Pomodoro"),
        ("Me resulta útil explicar un concepto o procedimiento a otra persona o escribirlo para asegurarme de que lo entiendo.", "Feynman"),
        ("Suelo repasar conceptos y fórmulas varias veces distribuidas en el tiempo para recordarlos mejor.", "Leitner"),
        ("Me concentro mejor si divido mis sesiones de estudio en bloques pequeños y no estudio durante períodos muy largos.", "Pomodoro"),
        ("Me gusta comprender profundamente los pasos de resolución de problemas antes de pasar a otros ejercicios.", "Feynman"),
        ("Me resulta más fácil recordar fórmulas, definiciones o reglas cuando las repaso varias veces o uso tarjetas de memoria.", "Leitner"),
        ("Prefiero estudiar resolviendo problemas prácticos y explicando cada paso mientras lo hago.", "Pomodoro_Feynman"),
        ("Me organizo revisando mis apuntes o resúmenes varias veces después de la clase para reforzar mi memoria.", "Leitner"),
        ("Me distraigo fácilmente si estudio sin pausas cortas y definidas.", "Pomodoro"),
        ("Cuando estudio, me gusta combinar comprensión activa (entender cada paso) con práctica regular de ejercicios.", "Feynman_Pomodoro"),
    ]

    for texto, metodo in preguntas:
        PreguntaPerfil.objects.update_or_create(texto=texto, defaults={"metodo": metodo})


def revertir_preguntas(apps, schema_editor):
    PreguntaPerfil = apps.get_model("Aprendizaje_adaptativo", "PreguntaPerfil")
    PreguntaPerfil.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("Aprendizaje_adaptativo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(cargar_preguntas, revertir_preguntas),
    ]
