# Generated by Django 5.2 on 2025-11-23 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aprendizaje_adaptativo', '0004_cargar_cursos_y_temas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaDificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('metodo_estudio', models.CharField(max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aprendizaje_adaptativo.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tema')},
            },
        ),
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('estudio', 'Estudio'), ('descanso', 'Descanso'), ('repaso', 'Repaso')], default='estudio', max_length=10)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('numero_sesion', models.IntegerField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_estudio', to=settings.AUTH_USER_MODEL)),
                ('tema_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='Aprendizaje_adaptativo.temadificultad')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionAdaptativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_sesiones', models.IntegerField()),
                ('sesiones_completadas', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
                ('tema_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='Aprendizaje_adaptativo.temadificultad')),
            ],
        ),
    ]
