# Generated by Django 5.2 on 2025-11-24 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aprendizaje_adaptativo', '0005_temadificultad_sesionestudio_planificacionadaptativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionMetodoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_principal', models.CharField(max_length=20)),
                ('metodo_complementario', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(help_text='Descripción breve del método sugerido')),
                ('razon', models.TextField(help_text='Razón por la cual fue elegido este método')),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='Aprendizaje_adaptativo.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recomendacion'],
            },
        ),
    ]
