# Generated by Django 5.2 on 2025-12-01 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Aprendizaje_adaptativo",
            "0005_temadificultad_sesionestudio_planificacionadaptativa",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrioridadMetodoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prioridad_1",
                    models.CharField(
                        choices=[
                            ("Pomodoro", "Pomodoro"),
                            ("Feynman", "Feynman"),
                            ("Leitner", "Leitner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridad_2",
                    models.CharField(
                        choices=[
                            ("Pomodoro", "Pomodoro"),
                            ("Feynman", "Feynman"),
                            ("Leitner", "Leitner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridad_3",
                    models.CharField(
                        choices=[
                            ("Pomodoro", "Pomodoro"),
                            ("Feynman", "Feynman"),
                            ("Leitner", "Leitner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tema",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prioridades",
                        to="Aprendizaje_adaptativo.tema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecomendacionEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodo_recomendado", models.CharField(max_length=20)),
                ("razon", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Aprendizaje_adaptativo.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
