# Generated by Django 5.2 on 2025-12-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aprendizaje_adaptativo', '0006_recomendacionmetodoestudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temadificultad',
            name='metodo_estudio',
        ),
    ]
