# Generated by Django 5.2 on 2025-06-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Calendario", "0002_rename_duracion_actividadnoacademica_horafin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_desarrollo", "En desarrollo"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_estado", models.DateTimeField(auto_now=True)),
                (
                    "tarea",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estado_actual",
                        to="Calendario.tarea",
                    ),
                ),
            ],
        ),
    ]
