# Generated by Django 5.2 on 2025-06-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tareas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadotarea",
            name="estado",
            field=models.CharField(
                choices=[
                    ("inicio", "Inicio"),
                    ("en_desarrollo", "En desarrollo"),
                    ("finalizado", "Finalizado"),
                    ("entregado", "Entregado"),
                ],
                default="inicio",
                max_length=20,
            ),
        ),
    ]
