# Generated by Django 5.2 on 2025-06-18 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Calendario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="actividadnoacademica",
            old_name="duracion",
            new_name="horaFin",
        ),
        migrations.AddField(
            model_name="actividadnoacademica",
            name="repetir",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="actividadnoacademica",
            name="semanas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                ("repetir", models.BooleanField(default=False)),
                ("semanas", models.IntegerField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=100)),
                ("temas", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("fechaEntrega", models.DateField()),
                ("horaEntrega", models.TimeField()),
                ("fechaRealizacion", models.DateField()),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                ("complejidad", models.IntegerField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ActividadAcademica",
        ),
    ]
