# Generated by Django 5.2 on 2025-06-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Calendario", "0002_rename_duracion_actividadnoacademica_horafin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
