# Generated by Django 5.2 on 2025-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0003_tarea_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='Inicio', max_length=20),
        ),
    ]
