# Generated by Django 5.2 on 2025-07-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0004_tarea_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
    ]
