# Generated by Django 5.2 on 2025-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendario', '0005_remove_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('en_desarrollo', 'En desarrollo'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='inicio', max_length=20),
        ),
    ]
