# Generated by Django 5.2 on 2025-06-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_fin',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
