# Generated by Django 5.2 on 2025-06-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificacion', '0002_remove_actividad_fecha_fin_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sugerencia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActividadNoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('repetir', models.BooleanField(default=False)),
                ('semanas', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_no_academicas', to='Notificacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('repetir', models.BooleanField(default=False)),
                ('semanas', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='Notificacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('temas', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='Notificacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fechaEntrega', models.DateField()),
                ('horaEntrega', models.TimeField()),
                ('fechaRealizacion', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('complejidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='Notificacion.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
