# Generated by Django 5.2 on 2025-06-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificacion', '0003_usuario_notificacion_usuario_sugerencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
