# Generated by Django 5.2 on 2025-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0002_alter_usuariopersonalizado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='notificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='sugerencia',
            field=models.BooleanField(default=False),
        ),
    ]
