# Generated by Django 5.2 on 2025-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0003_usuariopersonalizado_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='notificacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='sugerencia',
            field=models.BooleanField(default=True),
        ),
    ]
