# Generated by Django 5.2 on 2025-07-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0005_alter_usuariopersonalizado_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='notificacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='sugerencia',
            field=models.BooleanField(default=True),
        ),
    ]
